apiVersion: apps/v1
kind: Deployment
metadata:
  name: silentmoon-webapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: silentmoon-webapi
  template:
    metadata:
      labels:
        app: silentmoon-webapi
    spec:
      containers:
        - name: silentmoon-webapi
          image: myapi-dev-image:latest   # Docker image adın
          imagePullPolicy: Never          # Local image kullan
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: silentmoon-webapi-service
spec:
  type: LoadBalancer
  selector:
    app: silentmoon-webapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080